const playerCheatsPS = [
  {
    id: 1,
    nome: "Todas as armas",
    descricao:
      "TRIÂNGULO, R2, ESQUERDA, L1, X, DIREITA, TRIÂNGULO, BAIXO, QUADRADO, L1, L1, L1",
    plataforma: "PS",
    secao: "Jogador",
    imagems: [
      "../assets/icons/ps/ps_Triangulo.svg",
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_X.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Triangulo.svg",
      "../assets/icons/ps/ps_Baixo.svg",
      "../assets/icons/ps/ps_Quadrado.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L1.svg",
    ],
  },
  {
    id: 2,
    nome: "Vida máxima + armadura",
    descricao:
      "CÍRCULO, L1, TRIÂNGULO, R2, X, QUADRADO, CÍRCULO, DIREITA, QUADRADO, L1, L1, L1",
    plataforma: "PS",
    secao: "Jogador",
    imagems: [
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_Triangulo.svg",
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_X.svg",
      "../assets/icons/ps/ps_Quadrado.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Quadrado.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L1.svg",
    ],
  },
  {
    id: 3,
    nome: "Invencibilidade por 5 minutos",
    descricao:
      "DIREITA, X, DIREITA, ESQUERDA, DIREITA, R1, DIREITA, ESQUERDA, X, TRIANGULO",
    plataforma: "PS",
    secao: "Jogador",
    imagems: [
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_X.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_X.svg",
      "../assets/icons/ps/ps_Triangulo.svg",
    ],
  },
  {
    id: 4,
    nome: "Diminuir nível de procurado (uma estrela a cada ativação)",
    descricao:
      "R1, R1, CÍRCULO, R2, DIREITA, ESQUERDA, DIREITA, ESQUERDA, DIREITA, ESQUERDA",
    plataforma: "PS",
    secao: "Jogador",
    imagems: [
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
    ],
  },
  {
    id: 5,
    nome: "Aumentar nível de procurado (uma estrela a cada ativação)",
    descricao:
      "R1, R1, CÍRCULO, R2, ESQUERDA, DIREITA, ESQUERDA, DIREITA, ESQUERDA, DIREITA",
    plataforma: "PS",
    secao: "Jogador",
    imagems: [
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
    ],
  },
  {
    id: 6,
    nome: "Recarga de capacidade especial",
    descricao: "X, X, QUADRADO, R1, L1, X, DIREITA, ESQUERDA, X",
    plataforma: "PS",
    secao: "Jogador",
    imagems: [
      "../assets/icons/ps/ps_X.svg",
      "../assets/icons/ps/ps_X.svg",
      "../assets/icons/ps/ps_Quadrado.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_X.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_X.svg",
    ],
  },
  {
    id: 7,
    nome: "Munição explosiva",
    descricao:
      "DIREITA, QUADRADO, X, ESQUERDA, R1, R2, ESQUERDA, DIREITA, DIREITA, L1, L1, L1",
    plataforma: "PS",
    secao: "Jogador",
    imagems: [
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Quadrado.svg",
      "../assets/icons/ps/ps_X.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L1.svg",
    ],
  },
  {
    id: 8,
    nome: "Munição flamejante",
    descricao:
      "L1, R1, QUADRADO, R1, ESQUERDA, R2, R1, ESQUERDA, QUADRADO, DIREITA, L1, L1",
    plataforma: "PS",
    secao: "Jogador",
    imagems: [
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_Quadrado.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Quadrado.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L1.svg",
    ],
  },
  {
    id: 9,
    nome: "Ataques corpo a corpo explosivos",
    descricao:
      "DIREITA, ESQUERDA, X, TRIÂNGULO, R1, CÍRCULO, CÍRCULO, CÍRCULO, L2",
    plataforma: "PS",
    secao: "Jogador",
    imagems: [
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_X.svg",
      "../assets/icons/ps/ps_Triangulo.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_L2.svg",
    ],
  },
  {
    id: 10,
    nome: "Super pulo",
    descricao:
      "ESQUERDA, ESQUERDA, TRIÂNGULO, TRIÂNGULO, DIREITA, DIREITA, ESQUERDA, DIREITA, QUADRADO, R1, R2",
    plataforma: "PS",
    secao: "Jogador",
    imagems: [
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Triangulo.svg",
      "../assets/icons/ps/ps_Triangulo.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Quadrado.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_R2.svg",
    ],
  },
  {
    id: 11,
    nome: "Paraquedas",
    descricao:
      "ESQUERDA, DIREITA, L1, L2, R1, R2, R2, ESQUERDA, ESQUERDA, DIREITA, L1",
    plataforma: "PS",
    secao: "Jogador",
    imagems: [
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_L1.svg",
    ],
  },
  {
    id: 12,
    nome: "Queda livre",
    descricao:
      "L1, L2, R1, R2, ESQUERDA, DIREITA, ESQUERDA, DIREITA, L1, L2, R1, R2, ESQUERDA, DIREITA, ESQUERDA, DIREITA",
    plataforma: "PS",
    secao: "Jogador",
    imagems: [
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
    ],
  },
  {
    id: 13,
    nome: "Modo bêbado",
    descricao:
      "TRIÂNGULO, DIREITA, DIREITA, ESQUERDA, DIREITA, QUADRADO, CÍRCULO, ESQUERDA",
    plataforma: "PS",
    secao: "Jogador",
    imagems: [
      "../assets/icons/ps/ps_Triangulo.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Quadrado.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
    ],
  },
  {
    id: 14,
    nome: "Corrida rápida",
    descricao: "TRIÂNGULO, ESQUERDA, DIREITA, DIREITA, L2, L1, QUADRADO",
    plataforma: "PS",
    secao: "Jogador",
    imagems: [
      "../assets/icons/ps/ps_Triangulo.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_Quadrado.svg",
    ],
  },
  {
    id: 15,
    nome: "Nadar rápida",
    descricao:
      "ESQUERDA, ESQUERDA, L1, DIREITA, DIREITA, R2, ESQUERDA, L2, DIREITA",
    plataforma: "PS",
    secao: "Jogador",
    imagems: [
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_Direita.svg",
    ],
  },
  {
    id: 16,
    nome: "Mira em câmera lenta",
    descricao:
      "QUADRADO, L2, R1, TRIÂNGULO, ESQUERDA, QUADRADO, L2, DIREITA, X",
    plataforma: "PS",
    secao: "Jogador",
    imagems: [
      "../assets/icons/ps/ps_Quadrado.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_Triangulo.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Quadrado.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_X.svg",
    ],
  },
];

const worldCheatsPS = [
  {
    id: 1,
    nome: "Mudar o clima",
    descricao: "R2, X, L1, L1, L2, L2, L2, QUADRADO",
    plataforma: "PS",
    secao: "Mundo",
    imagems: [
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_X.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_Quadrado.svg",
    ],
  },
  {
    id: 2,
    nome: "Modo drift",
    descricao: "TRIÂNGULO, R1, R1, ESQUERDA, R1, L1, R2, L1",
    plataforma: "PS",
    secao: "Mundo",
    imagems: [
      "../assets/icons/ps/ps_Triangulo.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_L1.svg",
    ],
  },
  {
    id: 3,
    nome: "Câmera lenta",
    descricao: "TRIÂNGULO, ESQUERDA, DIREITA, DIREITA, QUADRADO, R2, R1",
    plataforma: "PS",
    secao: "Mundo",
    imagems: [
      "../assets/icons/ps/ps_Triangulo.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Quadrado.svg",
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_R1.svg",
    ],
  },
  {
    id: 4,
    nome: "Gravidade lunar",
    descricao:
      "ESQUERDA, ESQUERDA, L1, R1, L1, DIREITA, ESQUERDA, L1, ESQUERDA",
    plataforma: "PS",
    secao: "Mundo",
    imagems: [
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
    ],
  },
];

const vehicleCheatsPS = [
  {
    id: 1,
    nome: "Bicicleta BMX",
    descricao:
      "ESQUERDA, ESQUERDA, DIREITA, DIREITA, ESQUERDA, DIREITA, QUADRADO, CÍRCULO, TRIÂNGULO, R1, R2",
    plataforma: "PS",
    secao: "Veículos",
    ilustracao: "../assets/img/vehicles/bmx.png",
    imagems: [
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Quadrado.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_Triangulo.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_R2.svg",
    ],
  },
  {
    id: 2,
    nome: "Helicóptero Buzzard",
    descricao:
      "CÍRCULO, CÍRCULO, L1, CÍRCULO, CÍRCULO, CÍRCULO, L1, L2, R1, TRIÂNGULO, CÍRCULO, TRIÂNGULO",
    plataforma: "PS",
    secao: "Veículos",
    ilustracao: "../assets/img/vehicles/buzzard.png",
    imagems: [
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_X.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_Quadrado.svg",
    ],
  },
  {
    id: 3,
    nome: "Carrinho de Golfe Caddy",
    descricao: "CÍRCULO, L1, ESQUERDA, R1, L2, X, R1, L1, CÍRCULO, X",
    plataforma: "PS",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_X.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_X.svg",
    ],
  },
  {
    id: 4,
    nome: "Carro Comet",
    descricao: "R1, CÍRCULO, R2, DIREITA, L1, L2, X, X, QUADRADO, R1",
    plataforma: "PS",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_X.svg",
      "../assets/icons/ps/ps_X.svg",
      "../assets/icons/ps/ps_Quadrado.svg",
      "../assets/icons/ps/ps_R1.svg",
    ],
  },

  {
    id: 5,
    nome: "Avião Duster",
    descricao:
      "DIREITA, ESQUERDA, R1, R1, R1, ESQUERDA, TRIÂNGULO, TRIÂNGULO, X, CÍRCULO, L1, L1",
    plataforma: "PS",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Triangulo.svg",
      "../assets/icons/ps/ps_Triangulo.svg",
      "../assets/icons/ps/ps_X.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L1.svg",
    ],
  },
  {
    id: 6,
    nome: "Carro Limousine",
    descricao: "R2, DIREITA, L2, ESQUERDA, ESQUERDA, R1, L1, CÍRCULO, DIREITA",
    plataforma: "PS",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_Direita.svg",
    ],
  },
  {
    id: 7,
    nome: "Moto PCJ-600",
    descricao:
      "R1, DIREITA, ESQUERDA, DIREITA, R2, ESQUERDA, DIREITA, QUADRADO, DIREITA, L2, L1, L1",
    plataforma: "PS",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Quadrado.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L1.svg",
    ],
  },
  {
    id: 8,
    nome: "Carro Rapid GT",
    descricao:
      "R2, L1, CÍRCULO, DIREITA, L1, R1, DIREITA, ESQUERDA, CÍRCULO, R2",
    plataforma: "PS",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_R2.svg",
    ],
  },

  {
    id: 9,
    nome: "Moto Sanchez",
    descricao:
      "CÍRCULO, X, L1, CÍRCULO, CÍRCULO, L1, CÍRCULO, R1, R2, L2, L1, L1",
    plataforma: "PS",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_X.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_R2.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L1.svg",
    ],
  },
  {
    id: 10,
    nome: "Avião de Acrobacias",
    descricao:
      "CÍRCULO, DIREITA, L1, L2, ESQUERDA, R1, L1, L1, ESQUERDA, ESQUERDA, X, TRIÂNGULO",
    plataforma: "PS",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_Direita.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L2.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_X.svg",
      "../assets/icons/ps/ps_Triangulo.svg",
    ],
  },
  {
    id: 11,
    nome: "Caminhão de Lixo Trashmaster",
    descricao:
      "CÍRCULO, R1, CÍRCULO, R1, ESQUERDA, ESQUERDA, R1, L1, CÍRCULO, DIREITA",
    plataforma: "PS",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_Esquerda.svg",
      "../assets/icons/ps/ps_R1.svg",
      "../assets/icons/ps/ps_L1.svg",
      "../assets/icons/ps/ps_Bolinha.svg",
      "../assets/icons/ps/ps_Direita.svg",
    ],
  },
];

const playerCheatsXBX = [
  {
    id: 1,
    nome: "Todas as armas",
    descricao: "Y, RT, ESQUERDA, LB, A, DIREITA, Y, BAIXO, X, LB, LB, LB",
    plataforma: "XBOX",
    secao: "Jogador",
    imagems: [
      "../assets/icons/xbox/xb_Y.svg",
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_A.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Y.svg",
      "../assets/icons/xbox/xb_Baixo.svg",
      "../assets/icons/xbox/xb_X.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LB.svg",
    ],
  },
  {
    id: 2,
    nome: "Vida máxima + armadura",
    descricao: "B, LB, Y, RT, A, X, B, DIREITA, X, LB, LB, LB",
    plataforma: "XBOX",
    secao: "Jogador",
    imagems: [
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_Y.svg",
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_A.svg",
      "../assets/icons/xbox/xb_X.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_X.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LB.svg",
    ],
  },
  {
    id: 3,
    nome: "Invencibilidade por 5 minutos",
    descricao:
      "DIREITA, A, DIREITA, ESQUERDA, DIREITA, RB, DIREITA, ESQUERDA, A, Y",
    plataforma: "XBOX",
    secao: "Jogador",
    imagems: [
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_A.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_A.svg",
      "../assets/icons/xbox/xb_Y.svg",
    ],
  },
  {
    id: 4,
    nome: "Diminuir nível de procurado (uma estrela a cada ativação)",
    descricao:
      "RB, RB, B, RT, DIREITA, ESQUERDA, DIREITA, ESQUERDA, DIREITA, ESQUERDA",
    plataforma: "XBOX",
    secao: "Jogador",
    imagems: [
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
    ],
  },
  {
    id: 5,
    nome: "Aumentar nível de procurado (uma estrela a cada ativação)",
    descricao:
      "RB, RB, B, RT, ESQUERDA, DIREITA, ESQUERDA, DIREITA, ESQUERDA, DIREITA",
    plataforma: "XBOX",
    secao: "Jogador",
    imagems: [
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
    ],
  },
  {
    id: 6,
    nome: "Recarga de capacidade especial",
    descricao: "A, A, X, RB, LB, A, DIREITA, ESQUERDA, A",
    plataforma: "XBOX",
    secao: "Jogador",
    imagems: [
      "../assets/icons/xbox/xb_A.svg",
      "../assets/icons/xbox/xb_A.svg",
      "../assets/icons/xbox/xb_X.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_A.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_A.svg",
    ],
  },
  {
    id: 7,
    nome: "Munição explosiva",
    descricao:
      "DIREITA, X, A, ESQUERDA, RB, RT, ESQUERDA, DIREITA, DIREITA, LB, LB, LB",
    plataforma: "XBOX",
    secao: "Jogador",
    imagems: [
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_X.svg",
      "../assets/icons/xbox/xb_A.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LB.svg",
    ],
  },
  {
    id: 8,
    nome: "Munição flamejante",
    descricao: "LB, RB, X, RB, ESQUERDA, RT, RB, ESQUERDA, X, DIREITA, LB, LB",
    plataforma: "XBOX",
    secao: "Jogador",
    imagems: [
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_X.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_X.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LB.svg",
    ],
  },
  {
    id: 9,
    nome: "Ataques corpo a corpo explosivos",
    descricao: "DIREITA, ESQUERDA, A, Y, RB, B, B, B, LT",
    plataforma: "XBOX",
    secao: "Jogador",
    imagems: [
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_A.svg",
      "../assets/icons/xbox/xb_Y.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_LT.svg",
    ],
  },
  {
    id: 10,
    nome: "Super pulo",
    descricao:
      "ESQUERDA, ESQUERDA, Y, Y, DIREITA, DIREITA, ESQUERDA, DIREITA, X, RB, RT",
    plataforma: "XBOX",
    secao: "Jogador",
    imagems: [
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Y.svg",
      "../assets/icons/xbox/xb_Y.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_X.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_RT.svg",
    ],
  },
  {
    id: 11,
    nome: "Paraquedas",
    descricao:
      "ESQUERDA, DIREITA, LB, LT, RB, RT, RT, ESQUERDA, ESQUERDA, DIREITA, LB",
    plataforma: "XBOX",
    secao: "Jogador",
    imagems: [
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_LB.svg",
    ],
  },
  {
    id: 12,
    nome: "Queda livre",
    descricao:
      "LB, LT, RB, RT, ESQUERDA, DIREITA, ESQUERDA, DIREITA, LB, LT, RB, RT, ESQUERDA, DIREITA, ESQUERDA, DIREITA",
    plataforma: "XBOX",
    secao: "Jogador",
    imagems: [
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
    ],
  },
  {
    id: 13,
    nome: "Modo bêbado",
    descricao: "Y, DIREITA, DIREITA, ESQUERDA, DIREITA, X, B, ESQUERDA",
    plataforma: "XBOX",
    secao: "Jogador",
    imagems: [
      "../assets/icons/xbox/xb_Y.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_X.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
    ],
  },
  {
    id: 14,
    nome: "Corrida rápida",
    descricao: "Y, ESQUERDA, DIREITA, DIREITA, LT, LB, X",
    plataforma: "XBOX",
    secao: "Jogador",
    imagems: [
      "../assets/icons/xbox/xb_Y.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_X.svg",
    ],
  },
  {
    id: 15,
    nome: "Nadar rápida",
    descricao:
      "ESQUERDA, ESQUERDA, LB, DIREITA, DIREITA, RT, ESQUERDA, LT, DIREITA",
    plataforma: "XBOX",
    secao: "Jogador",
    imagems: [
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_Direita.svg",
    ],
  },
  {
    id: 16,
    nome: "Mira em câmera lenta",
    descricao: "X, LT, RB, Y, ESQUERDA, X, LT, DIREITA, A",
    plataforma: "XBOX",
    secao: "Jogador",
    imagems: [
      "../assets/icons/xbox/xb_X.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_Y.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_X.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_A.svg",
    ],
  },
];

const worldCheatsXBX = [
  {
    id: 1,
    nome: "Mudar o clima",
    descricao: "RT, A, LB, LB, LT, LT, LT, X",
    plataforma: "XBOX",
    secao: "Mundo",
    imagems: [
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_A.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_X.svg",
    ],
  },
  {
    id: 2,
    nome: "Modo drift",
    descricao: "Y, RB, RB, ESQUERDA, RB, LB, RT, LB",
    plataforma: "XBOX",
    secao: "Mundo",
    imagems: [
      "../assets/icons/xbox/xb_Y.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_LB.svg",
    ],
  },
  {
    id: 3,
    nome: "Câmera lenta",
    descricao: "Y, ESQUERDA, DIREITA, DIREITA, X, RT, RB",
    plataforma: "XBOX",
    secao: "Mundo",
    imagems: [
      "../assets/icons/xbox/xb_Y.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_X.svg",
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_RB.svg",
    ],
  },
  {
    id: 4,
    nome: "Gravidade lunar",
    descricao:
      "ESQUERDA, ESQUERDA, LB, RB, LB, DIREITA, ESQUERDA, LB, ESQUERDA",
    plataforma: "XBOX",
    secao: "Mundo",
    imagems: [
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
    ],
  },
];

const vehicleCheatsXBX = [
  {
    id: 1,
    nome: "Bicicleta BMX",
    descricao:
      "ESQUERDA, ESQUERDA, DIREITA, DIREITA, ESQUERDA, DIREITA, X, B, Y, RB, RT",
    plataforma: "XBOX",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_X.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_Y.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_RT.svg",
    ],
  },
  {
    id: 2,
    nome: "Helicóptero Buzzard",
    descricao: "B, B, LB, B, B, B, LB, LT, RB, Y, B, Y",
    plataforma: "XBOX",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_A.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_X.svg",
    ],
  },
  {
    id: 3,
    nome: "Carrinho de Golfe Caddy",
    descricao: "B, LB, ESQUERDA, RB, LT, A, RB, LB, B, A",
    plataforma: "XBOX",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_A.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_A.svg",
    ],
  },
  {
    id: 4,
    nome: "Carro Comet",
    descricao: "RB, B, RT, DIREITA, LB, LT, A, A, X, RB",
    plataforma: "XBOX",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_A.svg",
      "../assets/icons/xbox/xb_A.svg",
      "../assets/icons/xbox/xb_X.svg",
      "../assets/icons/xbox/xb_RB.svg",
    ],
  },

  {
    id: 5,
    nome: "Avião Duster",
    descricao: "DIREITA, ESQUERDA, RB, RB, RB, ESQUERDA, Y, Y, A, B, LB, LB",
    plataforma: "XBOX",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Y.svg",
      "../assets/icons/xbox/xb_Y.svg",
      "../assets/icons/xbox/xb_A.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LB.svg",
    ],
  },
  {
    id: 6,
    nome: "Carro Limousine",
    descricao: "RT, DIREITA, LT, ESQUERDA, ESQUERDA, RB, LB, B, DIREITA",
    plataforma: "XBOX",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_Direita.svg",
    ],
  },
  {
    id: 7,
    nome: "Moto PCJ-600",
    descricao:
      "RB, DIREITA, ESQUERDA, DIREITA, RT, ESQUERDA, DIREITA, X, DIREITA, LT, LB, LB",
    plataforma: "XBOX",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_X.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LB.svg",
    ],
  },
  {
    id: 8,
    nome: "Carro Rapid GT",
    descricao: "RT, LB, B, DIREITA, LB, RB, DIREITA, ESQUERDA, B, RT",
    plataforma: "XBOX",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_RT.svg",
    ],
  },

  {
    id: 9,
    nome: "Moto Sanchez",
    descricao: "B, A, LB, B, B, LB, B, RB, RT, LT, LB, LB",
    plataforma: "XBOX",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_A.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_RT.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LB.svg",
    ],
  },
  {
    id: 10,
    nome: "Avião de Acrobacias",
    descricao:
      "B, DIREITA, LB, LT, ESQUERDA, RB, LB, LB, ESQUERDA, ESQUERDA, A, Y",
    plataforma: "XBOX",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_Direita.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LT.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_A.svg",
      "../assets/icons/xbox/xb_Y.svg",
    ],
  },
  {
    id: 11,
    nome: "Caminhão de Lixo Trashmaster",
    descricao: "B, RB, B, RB, ESQUERDA, ESQUERDA, RB, LB, B, DIREITA",
    plataforma: "XBOX",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_Esquerda.svg",
      "../assets/icons/xbox/xb_RB.svg",
      "../assets/icons/xbox/xb_LB.svg",
      "../assets/icons/xbox/xb_B.svg",
      "../assets/icons/xbox/xb_Direita.svg",
    ],
  },
];

const playerCheatsCOMP = [
  {
    id: 1,
    nome: "Todas as armas",
    descricao: "TOOLUP",
    plataforma: "COMP",
    secao: "Jogador",
    imagems: [
      "../assets/icons/comp/T.svg",
      "../assets/icons/comp/O.svg",
      "../assets/icons/comp/O.svg",
      "../assets/icons/comp/L.svg",
      "../assets/icons/comp/U.svg",
      "../assets/icons/comp/P.svg",
    ],
  },
  {
    id: 2,
    nome: "Vida máxima + armadura",
    descricao: "TURTLE",
    plataforma: "COMP",
    secao: "Jogador",
    imagems: [
      "../assets/icons/comp/T.svg",
      "../assets/icons/comp/U.svg",
      "../assets/icons/comp/R.svg",
      "../assets/icons/comp/T.svg",
      "../assets/icons/comp/L.svg",
      "../assets/icons/comp/E.svg",
    ],
  },
  {
    id: 3,
    nome: "Invencibilidade por 5 minutos",
    descricao: "PAINKILLER",
    plataforma: "COMP",
    secao: "Jogador",
    imagems: [
      "../assets/icons/comp/P.svg",
      "../assets/icons/comp/A.svg",
      "../assets/icons/comp/I.svg",
      "../assets/icons/comp/N.svg",
      "../assets/icons/comp/K.svg",
      "../assets/icons/comp/I.svg",
      "../assets/icons/comp/L.svg",
      "../assets/icons/comp/L.svg",
      "../assets/icons/comp/E.svg",
      "../assets/icons/comp/R.svg",
    ],
  },
  {
    id: 4,
    nome: "Diminuir nível de procurado (uma estrela a cada ativação)",
    descricao: "LAWYERUP",
    plataforma: "COMP",
    secao: "Jogador",
    imagems: [
      "../assets/icons/comp/L.svg",
      "../assets/icons/comp/A.svg",
      "../assets/icons/comp/W.svg",
      "../assets/icons/comp/Y.svg",
      "../assets/icons/comp/E.svg",
      "../assets/icons/comp/R.svg",
      "../assets/icons/comp/U.svg",
      "../assets/icons/comp/P.svg",
    ],
  },
  {
    id: 5,
    nome: "Aumentar nível de procurado (uma estrela a cada ativação)",
    descricao: "FUGITIVE",
    plataforma: "COMP",
    secao: "Jogador",
    imagems: [
      "../assets/icons/comp/F.svg",
      "../assets/icons/comp/U.svg",
      "../assets/icons/comp/G.svg",
      "../assets/icons/comp/I.svg",
      "../assets/icons/comp/T.svg",
      "../assets/icons/comp/I.svg",
      "../assets/icons/comp/V.svg",
      "../assets/icons/comp/E.svg",
    ],
  },
  {
    id: 6,
    nome: "Recarga de capacidade especial",
    descricao: "POWERUP",
    plataforma: "COMP",
    secao: "Jogador",
    imagems: [
      "../assets/icons/comp/P.svg",
      "../assets/icons/comp/O.svg",
      "../assets/icons/comp/W.svg",
      "../assets/icons/comp/E.svg",
      "../assets/icons/comp/R.svg",
      "../assets/icons/comp/U.svg",
      "../assets/icons/comp/P.svg",
    ],
  },
  {
    id: 8,
    nome: "Munição flamejante",
    descricao: "INCENDIARY",
    plataforma: "COMP",
    secao: "Jogador",
    imagems: [
      "../assets/icons/comp/I.svg",
      "../assets/icons/comp/N.svg",
      "../assets/icons/comp/C.svg",
      "../assets/icons/comp/E.svg",
      "../assets/icons/comp/N.svg",
      "../assets/icons/comp/D.svg",
      "../assets/icons/comp/I.svg",
      "../assets/icons/comp/A.svg",
      "../assets/icons/comp/R.svg",
      "../assets/icons/comp/Y.svg",
    ],
  },
  {
    id: 9,
    nome: "Ataques corpo a corpo explosivos",
    descricao: "HOTHANDS",
    plataforma: "COMP",
    secao: "Jogador",
    imagems: [
      "../assets/icons/comp/H.svg",
      "../assets/icons/comp/O.svg",
      "../assets/icons/comp/T.svg",
      "../assets/icons/comp/H.svg",
      "../assets/icons/comp/A.svg",
      "../assets/icons/comp/N.svg",
      "../assets/icons/comp/D.svg",
      "../assets/icons/comp/S.svg",
    ],
  },
  {
    id: 11,
    nome: "Paraquedas",
    descricao: "SKYDIVE",
    plataforma: "COMP",
    secao: "Jogador",
    imagems: [
      "../assets/icons/comp/S.svg",
      "../assets/icons/comp/K.svg",
      "../assets/icons/comp/Y.svg",
      "../assets/icons/comp/D.svg",
      "../assets/icons/comp/I.svg",
      "../assets/icons/comp/V.svg",
      "../assets/icons/comp/E.svg",
    ],
  },
  {
    id: 12,
    nome: "Queda livre",
    descricao: "SKYFALL",
    plataforma: "COMP",
    secao: "Jogador",
    imagems: [
      "../assets/icons/comp/S.svg",
      "../assets/icons/comp/K.svg",
      "../assets/icons/comp/Y.svg",
      "../assets/icons/comp/F.svg",
      "../assets/icons/comp/A.svg",
      "../assets/icons/comp/L.svg",
      "../assets/icons/comp/L.svg",
    ],
  },
  {
    id: 13,
    nome: "Modo bêbado",
    descricao: "LIQUOR",
    plataforma: "COMP",
    secao: "Jogador",
    imagems: [
      "../assets/icons/comp/L.svg",
      "../assets/icons/comp/I.svg",
      "../assets/icons/comp/Q.svg",
      "../assets/icons/comp/U.svg",
      "../assets/icons/comp/O.svg",
      "../assets/icons/comp/R.svg",
    ],
  },
  {
    id: 14,
    nome: "Corrida rápida",
    descricao: "CATCHME",
    plataforma: "COMP",
    secao: "Jogador",
    imagems: [
      "../assets/icons/comp/C.svg",
      "../assets/icons/comp/A.svg",
      "../assets/icons/comp/T.svg",
      "../assets/icons/comp/C.svg",
      "../assets/icons/comp/H.svg",
      "../assets/icons/comp/M.svg",
      "../assets/icons/comp/E.svg",
    ],
  },
  {
    id: 16,
    nome: "Mira em câmera lenta",
    descricao: "DEADEYE",
    plataforma: "COMP",
    secao: "Jogador",
    imagems: [
      "../assets/icons/comp/D.svg",
      "../assets/icons/comp/E.svg",
      "../assets/icons/comp/A.svg",
      "../assets/icons/comp/D.svg",
      "../assets/icons/comp/E.svg",
      "../assets/icons/comp/Y.svg",
      "../assets/icons/comp/E.svg",
    ],
  },
];

const worldCheatsCOMP = [
  {
    id: 1,
    nome: "Mudar o clima",
    descricao: "MAKEITRAIN",
    plataforma: "COMP",
    secao: "Mundo",
    imagems: [
      "../assets/icons/comp/M.svg",
      "../assets/icons/comp/A.svg",
      "../assets/icons/comp/K.svg",
      "../assets/icons/comp/E.svg",
      "../assets/icons/comp/I.svg",
      "../assets/icons/comp/T.svg",
      "../assets/icons/comp/R.svg",
      "../assets/icons/comp/A.svg",
      "../assets/icons/comp/I.svg",
      "../assets/icons/comp/N.svg",
    ],
  },
  {
    id: 2,
    nome: "Modo drift",
    descricao: "SNOWDAY",
    plataforma: "COMP",
    secao: "Mundo",
    imagems: [
      "../assets/icons/comp/S.svg",
      "../assets/icons/comp/N.svg",
      "../assets/icons/comp/O.svg",
      "../assets/icons/comp/W.svg",
      "../assets/icons/comp/D.svg",
      "../assets/icons/comp/A.svg",
      "../assets/icons/comp/Y.svg",
    ],
  },
  {
    id: 3,
    nome: "Câmera lenta",
    descricao: "SLOWMO",
    plataforma: "COMP",
    secao: "Mundo",
    imagems: [
      "../assets/icons/comp/S.svg",
      "../assets/icons/comp/L.svg",
      "../assets/icons/comp/O.svg",
      "../assets/icons/comp/W.svg",
      "../assets/icons/comp/M.svg",
      "../assets/icons/comp/O.svg",
    ],
  },
  {
    id: 4,
    nome: "Gravidade lunar",
    descricao: "FLOATER",
    plataforma: "COMP",
    secao: "Mundo",
    imagems: [
      "../assets/icons/comp/F.svg",
      "../assets/icons/comp/L.svg",
      "../assets/icons/comp/O.svg",
      "../assets/icons/comp/A.svg",
      "../assets/icons/comp/T.svg",
      "../assets/icons/comp/E.svg",
      "../assets/icons/comp/R.svg",
    ],
  },
];

const vehicleCheatsCOMP = [
  {
    id: 1,
    nome: "Bicicleta BMX",
    descricao: "BANDIT",
    plataforma: "COMP",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/comp/B.svg",
      "../assets/icons/comp/A.svg",
      "../assets/icons/comp/N.svg",
      "../assets/icons/comp/D.svg",
      "../assets/icons/comp/I.svg",
      "../assets/icons/comp/T.svg",
    ],
  },
  {
    id: 2,
    nome: "Helicóptero Buzzard",
    descricao: "BUZZOFF",
    plataforma: "COMP",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/comp/B.svg",
      "../assets/icons/comp/U.svg",
      "../assets/icons/comp/Z.svg",
      "../assets/icons/comp/Z.svg",
      "../assets/icons/comp/O.svg",
      "../assets/icons/comp/F.svg",
      "../assets/icons/comp/F.svg",
    ],
  },
  {
    id: 4,
    nome: "Carro Comet",
    descricao: "COMET",
    plataforma: "COMP",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/comp/C.svg",
      "../assets/icons/comp/O.svg",
      "../assets/icons/comp/M.svg",
      "../assets/icons/comp/E.svg",
      "../assets/icons/comp/T.svg",
    ],
  },
  {
    id: 6,
    nome: "Carro Limousine",
    descricao: "VINEWOOD",
    plataforma: "COMP",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/comp/V.svg",
      "../assets/icons/comp/I.svg",
      "../assets/icons/comp/N.svg",
      "../assets/icons/comp/E.svg",
      "../assets/icons/comp/W.svg",
      "../assets/icons/comp/O.svg",
      "../assets/icons/comp/O.svg",
      "../assets/icons/comp/D.svg",
    ],
  },
  {
    id: 7,
    nome: "Moto PCJ-600",
    descricao: "ROCKET",
    plataforma: "COMP",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/comp/R.svg",
      "../assets/icons/comp/O.svg",
      "../assets/icons/comp/C.svg",
      "../assets/icons/comp/K.svg",
      "../assets/icons/comp/E.svg",
      "../assets/icons/comp/T.svg",
    ],
  },
  {
    id: 8,
    nome: "Carro Rapid GT",
    descricao: "RAPIDGT",
    plataforma: "COMP",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/comp/R.svg",
      "../assets/icons/comp/A.svg",
      "../assets/icons/comp/P.svg",
      "../assets/icons/comp/I.svg",
      "../assets/icons/comp/D.svg",
      "../assets/icons/comp/G.svg",
      "../assets/icons/comp/T.svg",
    ],
  },

  {
    id: 9,
    nome: "Moto Sanchez",
    descricao: "OFFROAD",
    plataforma: "COMP",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/comp/O.svg",
      "../assets/icons/comp/F.svg",
      "../assets/icons/comp/F.svg",
      "../assets/icons/comp/R.svg",
      "../assets/icons/comp/O.svg",
      "../assets/icons/comp/A.svg",
      "../assets/icons/comp/D.svg",
    ],
  },
  {
    id: 10,
    nome: "Avião de Acrobacias",
    descricao: "BARNSTORM",
    plataforma: "COMP",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/comp/B.svg",
      "../assets/icons/comp/A.svg",
      "../assets/icons/comp/R.svg",
      "../assets/icons/comp/N.svg",
      "../assets/icons/comp/S.svg",
      "../assets/icons/comp/T.svg",
      "../assets/icons/comp/O.svg",
      "../assets/icons/comp/R.svg",
      "../assets/icons/comp/M.svg",
    ],
  },
  {
    id: 11,
    nome: "Caminhão de Lixo Trashmaster",
    descricao: "TRASHED",
    plataforma: "COMP",
    secao: "Veículos",
    ilustracao: "*imagem*",
    imagems: [
      "../assets/icons/comp/T.svg",
      "../assets/icons/comp/R.svg",
      "../assets/icons/comp/A.svg",
      "../assets/icons/comp/S.svg",
      "../assets/icons/comp/H.svg",
      "../assets/icons/comp/E.svg",
      "../assets/icons/comp/D.svg",
    ],
  },
];
export {
  playerCheatsPS,
  worldCheatsPS,
  vehicleCheatsPS,
  playerCheatsXBX,
  worldCheatsXBX,
  vehicleCheatsXBX,
  playerCheatsCOMP,
  worldCheatsCOMP,
  vehicleCheatsCOMP,
};
